apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeployxyz
  labels:
    app: autodeployxyz
  namespace: namespace-workflow-1708428894602
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeployxyz
  template:
    metadata:
      labels:
        app: autodeployxyz
    spec:
      containers:
        - name: autodeployxyz
          image: acrworkflow1708428894602.azurecr.io/image-workflow-1708428894602:latest
          ports:
            - containerPort: 5000