apiVersion: v1
kind: Service
metadata:
  name: autodeployxyz
  namespace: namespace-workflow-1708428894602
spec:
  type: LoadBalancer
  selector:
    app: autodeployxyz
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000